shaders = {}

textures = {
	{"road", "texRep"},
	{"road2", "texRep"},
	{"ground", "texRep"},
	{"rails", "texRep"},
	{"lowground", "texRep"},
	{"bush", "texRep"},
	{"vehicletyres128", "texRep"},
	{"thread", "texRep"},
	{"CTP_tire_style1", "texRep"},
	{"CTP_tire_style2", "texRep"},
	{"tire_CTP", "texRep"},
	{"wheel_tire_SS", "texRep"},
	{"newtreeleavesb128", "texRep"},
	{"newtreeleaves128", "texRep"},
	{"Newtreed256", "texRep"},
	{"kb_ivy2_256", "texRep"},
	{"newhedgea", "texRep"},
	{"snowflakes", "texRep"},
	{"tiretrack", "texRep"},
	{"grass", "texRep"}
}

for k, v in pairs(textures) do
	shaders[v[1]] = dxCreateShader("data/shaders/" .. v[2] .. ".fx")
	texture = dxCreateTexture("data/textures/" .. v[1] .. ".png")
	dxSetShaderValue(shaders[v[1]], "gTexture", texture)
end

replaceTextures = {
	["snpedtest1"] = shaders["road"],
	["metpat64"] = shaders["lowground"],
	["ws_traintrax1"] = shaders["lowground"],
	["ws_traingravel"] = shaders["lowground"],
	["trainground2"] = shaders["lowground"],
	["heliconcrete"] = shaders["lowground"],
	["dt_road"] = shaders["road"],
	["dt_road_stoplinea"] = shaders["lowground"],
	["crossing_law"] = shaders["ground"],
	["trainground1"] = shaders["ground"],
	["sjmhoodlawn41"] = shaders["ground"],
	["sjmscorclawn"] = shaders["ground"],
	["scumtiles3_lae"] = shaders["ground"],
	["comptwall4"] = shaders["ground"],
	["comptroof1"] = shaders["ground"],
	["shingles1"] = shaders["ground"],
	["ws_rooftarmac1"] = shaders["ground"],
	["lasrmd2_sjm"] = shaders["ground"],
	["stormdrain2_nt"] = shaders["ground"],
	["stormdrain1_nt"] = shaders["ground"],
	["lasrmd3_sjm"] = shaders["ground"],
	["dirt64b2"] = shaders["ground"],
	["dirtgaz64b"] = shaders["ground"],
	["bow_abattoir_conc2"] = shaders["ground"],
	["backalley1_lae"] = shaders["ground"],
	["roof11l256"] = shaders["ground"],
	["sjmlahus28"] = shaders["ground"],
	["adet"] = shaders["ground"],
	["sjmscorclawn3"] = shaders["ground"],
	["newtreeleaves128"] = shaders["newtreeleavesb128"],
	["newtreed256"] = shaders["newtreeleavesb128"],
	["elm_treegrn"] = shaders["newtreeleaves128"],
	["planta256"] = shaders["newtreeleaves128"],
	["cos_hiwaymid_256"] = shaders["road"],
	["cos_hiwayout_256"] = shaders["ground"],
	["badmarb1_lan"] = shaders["ground"],
	["dockpave_256"] = shaders["ground"],
	["sidelatino1_lae"] = shaders["ground"],
	["grifnewtex1x_las"] = shaders["ground"],
	["grifnewtex1b"] = shaders["ground"],
	["cityhallroof"] = shaders["ground"],
	["pavemiddirt_law"] = shaders["ground"],
	["concretebigb256128"] = shaders["ground"],
	["sandnew_law"] = shaders["ground"],
	["venwalkway_law"] = shaders["ground"],
	["waterclear256"] = shaders["snow"],
	["pier69_ground1"] = shaders["ground"],
	["grasstype3"] = shaders["ground"],
	["redclifftop256"] = shaders["ground"],
	["desgreengrass"] = shaders["ground"],
	["rocktbrn128"] = shaders["ground"],
	["vehicletyres128"] = shaders["vehicletyres128"],
	["thread"] = shaders["thread"],
	["CTP_tire_style1"] = shaders["CTP_tire_style1"],
	["CTP_tire_style2"] = shaders["CTP_tire_style2"],
	["tire_CTP"] = shaders["tire_CTP"],
	["wheel_tire_SS"] = shaders["wheel_tire_SS"],
	["tardor9"] = shaders["ground"],
	["wgush1"] = shaders["ground"],
	["concretemanky"] = shaders["ground"],
	["pinelo128"] = shaders["newtreeleavesb128"],
	["oakleaf1"] = shaders["newtreeleavesb128"],
	["oakleaf2"] = shaders["newtreeleavesb128"],
	["stormdrain6"] = shaders["ground"],
	["block2"] = shaders["ground"],
	["golf_heavygrass"] = shaders["ground"],
	["sm_agave_1"] = shaders["newtreeleavesb128"],
	["sm_minipalm1"] = shaders["newtreeleavesb128"],
	["starflower3"] = shaders["newtreeleavesb128"],
	["indund_64"] = shaders["ground"],
	["newhedgea"] = shaders["newhedgea"],
	["bow_church_grass_gen"] = shaders["ground"],
	["greyground256"] = shaders["ground"],
	["bow_church_grass_alt"] = shaders["ground"],
	["golf_hedge1"] = shaders["newhedgea"],
	["ws_nicepave"] = shaders["ground"],
	["grassshort2long256"] = shaders["ground"],
	["pinebranch2"] = shaders["newtreeleaves128"],
	["beachwalk_law"] = shaders["ground"],
	["grass_128hv"] = shaders["ground"],
	["tar_1line256hv"] = shaders["road2"],
	["pavebsand256"] = shaders["ground"],
	["desgreengrassmix"] = shaders["ground"],
	["desertgryard256"] = shaders["ground"],
	["desertgravelgrassroad"] = shaders["ground"],
	["grassbrn2rockbrng"] = shaders["ground"],
	["roadnew4_512"] = shaders["road"],
	["des_dirt2grass"] = shaders["ground"],
	["desmud"] = shaders["ground"],
	["dirttracksgrass256"] = shaders["road"],
	["desmudtrail"] = shaders["road"],
	["desmudgrass"] = shaders["ground"],
	["elm_treegrn2"] = shaders["newtreeleaves128"],
	["desmuddesgrsblend"] = shaders["ground"],
	["desertstones256"] = shaders["ground"],
	["ws_hextile"] = shaders["ground"],
	["stormdrain3_nt"] = shaders["ground"],
	["tarmacplain_bank"] = shaders["ground"],
	["snpdwargrn1"] = shaders["ground"],
	["mono2_sfe"] = shaders["ground"],
	["mono1_sfe•"] = shaders["ground"],
	["grassgrn256"] = shaders["ground"],
	["newpavement"] = shaders["ground"],
	["mono3_sfe"] = shaders["ground"],
	["mono4_sfe"] = shaders["ground"],
	["tar_1line256hvblend"] = shaders["road2"],
	["hedge2"] = shaders["newhedgea"],
	["tar_1line256hvblend"] = shaders["road2"],
	["grassdead1"] = shaders["ground"],
	["forestfloor256"] = shaders["ground"],
	["lasclifface"] = shaders["ground"],
	["forestfloorgrass"] = shaders["ground"],
	["rocktbrn128blnd"] = shaders["ground"],
	["cs_rockdetail2"] = shaders["ground"],
	["desertgravelgrass256"] = shaders["newhedgea"],
	["aamanbev96x"] = shaders["ground"],
	["kb_ivy2_256"] = shaders["kb_ivy2_256"],
	["tar_1line256hvblenddrtdot"] = shaders["road2"],
	["tar_1line256hvblenddrt"] = shaders["road2"],
	["tar_freewyleft"] = shaders["road2"],
	["desgrassbrn_grn"] = shaders["ground"],
	["dirtblendlit"] = shaders["ground"],
	["grassbrn2rockbrn"] = shaders["ground"],
	["desgrassbrn"] = shaders["ground"],
	["grasstype4"] = shaders["ground"],
	["grasstype4_mudblend"] = shaders["ground"],
	["rocktq128_grass4blend"] = shaders["ground"],
	["txgrass1_1"] = shaders["kb_ivy2_256"],
	["tree19mi"] = shaders["newtreeleaves128"],
	["ws_patchygravel"] = shaders["ground"],
	["newcrop3"] = shaders["ground"],
	["bow_church_dirt"] = shaders["ground"],
	["grass4dirtytrans"] = shaders["ground"],
	["grasstype5_4"] = shaders["ground"],
	["grasstype5"] = shaders["ground"],
	["cw2_weeroad1"] = shaders["road"],
	["bullethitsmoke"] = shaders["snowflakes"],
	["particleskid"] = shaders["tiretrack"],
	["grasstype4_forestblend"] = shaders["ground"],
	["forestfloorblendded"] = shaders["road2○"],
	["forestfloor_sones256"] = shaders["ground"],
	["forestfloorblendded"] = shaders["ground"],
	["forest_rocks"] = shaders["ground"],
	["forestfloor3_forest"] = shaders["ground"],
	["forestfloor3"] = shaders["ground"],
	["cw2_mounttrail"] = shaders["ground"],
	["cw2_mounttrailblank"] = shaders["ground"],
	["rocktq128"] = shaders["ground"],
	["rock_country128"] = shaders["ground"],
	["rocktq128_forestblend"] = shaders["ground"],
	["rocktq128_forestblend2"] = shaders["ground"],
	["stones256"] = shaders["ground"],
	["mountainskree_stones256"] = shaders["road2"],
	["des_dirtgrassmixbmp"] = shaders["ground"],
	["des_dirtgrassmix_grass4"] = shaders["ground"],
	["des_dirtgrassmixb"] = shaders["ground"],
	["des_dirtgrassmixc"] = shaders["ground"],
	["grass4_des_dirt2"] = shaders["ground"],
	["cuntbrnclifftop"] = shaders["ground"],
	["cuntbrncliffbtmbmp"] = shaders["ground"],
	["forestfloor256_blenddirt"] = shaders["ground"],
	["sw_sand"] = shaders["ground"],
	["des_dirt1"] = shaders["ground"],
	["grasstype4blndtomud"] = shaders["road2"],
	["pavebsand256grassblended"] = shaders["ground"],
	["grasstype10"] = shaders["ground"],
	["grasstype4_10"] = shaders["ground"],
	["cw2_mountdirt"] = shaders["ground"],
	["cw2_mountdirt2grass"] = shaders["ground"],
	["cw2_mountdirtscree"] = shaders["ground"],
	["cw2_mountrock"] = shaders["ground"],
	["cw2_mountroad"] = shaders["road2"],
	["tar_freewyright"] = shaders["road2"],
	["ws_drysand2grass"] = shaders["ground"],
	["ws_drysand"] = shaders["ground"],
	["ws_wetdryblendsand"] = shaders["ground"],
	["ws_wetsand"] = shaders["ground"],
	["ws_freeway3"] = shaders["road"],
	["ws_freeway3blend"] = shaders["road"],
	["sf_road5"] = shaders["road"],
	["sf_pave6"] = shaders["ground"],
	["sf_junction5"] = shaders["ground"],
	["fancy_slab128"] = shaders["ground"],
	["newrockgrass_sfw"] = shaders["ground"],
	["cst_rock_coast_sfw"] = shaders["ground"],
	["sf_junction3"] = shaders["ground"],
	["fancy_slab128"] = shaders["ground"],
	["pavetilealley256128"] = shaders["road2"],
	["sf_tramline2"] = shaders["rails"],
	["sf_pave2"] = shaders["ground"],
	["sf_pave3"] = shaders["ground"],
	["sf_pave4"] = shaders["ground"],
	["sf_pave5"] = shaders["ground"],
	["ws_airpt_concrete"] = shaders["ground"],
	["cs_rockdetail2"] = shaders["ground"],
	["sw_stonesgrass"] = shaders["ground"],
	["grassbrn2rockbrng2"] = shaders["ground"],
	["sw_stones"] = shaders["ground"],
	["cs_rockdetail2"] = shaders["ground"],
	["dirttracksforest"] = shaders["road"],
	["sw_rockgrassb1"] = shaders["ground"],
	["sw_rockgrassb2"] = shaders["ground"],
	["sw_sandgrass4"] = shaders["ground"],
	["sw_rockgrass1"] = shaders["ground"],
	["carpark_128"] = shaders["ground"],
	["sw_newcorrug"] = shaders["ground"],
	["parking2plain"] = shaders["ground"],
	["parking2"] = shaders["ground"],
	["grass"] = shaders["ground"],
	["sw_corrug"] = shaders["ground"],
	["sw_crops"] = shaders["ground"],
	["sw_grassb01"] = shaders["ground"],
	["sw_grass01"] = shaders["ground"],
	["sw_dirt01lod"] = shaders["ground"],
	["sw_dirt01"] = shaders["ground"],
	["sw_cropslod"] = shaders["ground"],
	["sw_grass01a"] = shaders["ground"],
	["sw_farmroad01"] = shaders["road"],
	["des_dirt1grass"] = shaders["ground"],
	["hilltest2_las"] = shaders["kb_ivy2_256"],
	["desgreengrasstrckend"] = shaders["ground"],
	["roadnew4_256"] = shaders["road"],
	["des_dirt2"] = shaders["ground"],
	["sw_sandgrass"] = shaders["ground"],
	["desclifftypebsmix"] = shaders["ground"],
	["boardwalk_la"] = shaders["ground"],
	["cos_hiwayins_256"] = shaders["ground"],
	["sjmhoodlawn42b"] = shaders["ground"],
	["gb_nastybar08"] = shaders["ground"],
	["laroad_centre1"] = shaders["ground"],
	["kbpavement_test"] = shaders["ground"],
	["brickred2"] = shaders["ground"],
	["ws_carparknew2"] = shaders["ground"],
	["ws_carparknew1"] = shaders["ground"],
	["sl_sfngrass01"] = shaders["ground"],
	["sl_sfngrssdrt01"] = shaders["ground"],
	["desertgryard256grs2"] = shaders["ground"],
	["grassgrnbrn256"] = shaders["ground"],
	["concretenewb256"] = shaders["ground"],
	["ws_rotten_concrete1"] = shaders["ground"],
	["ws_corr_metal1"] = shaders["ground"],
	["ws_corr_plastic"] = shaders["ground"],
	["ws_carpark2"] = shaders["ground"],
	["ws_floortiles2"] = shaders["ground"],
	["ws_football_lines2"] = shaders["ground"],
	["ws_floortiles4"] = shaders["ground"],
	["ws_sub_pen_conc3"] = shaders["ground"],
	["des_grass2dirt1"] = shaders["ground"],
	["des_roadedge1"] = shaders["ground"],
	["des_roadedge2"] = shaders["ground"],
	["tar_1line256hvtodirt"] = shaders["road2"],
	["brngrss2stones"] = shaders["ground"],
	["des_yelrock"] = shaders["ground"],
	["des_dirttrack1"] = shaders["road2"],
	["des_dirttrack1r"] = shaders["road2"],
	["des_dirttrackl"] = shaders["road2"],
	["grasstype5_dirt"] = shaders["ground"],
	["rocktq128_dirt"] = shaders["ground"],
	["des_redrock2"] = shaders["ground"],
	["des_redrock1"] = shaders["ground"],
	["des_dirt2blend"] = shaders["ground"],
	["des_dirt2stones"] = shaders["ground"],
	["des_dirt2track"] = shaders["ground"],
	["des_dirt2 trackl"] = shaders["ground"],
	["des_dirtgravel"] = shaders["ground"],
	["desstones_dirt1"] = shaders["ground"],
	["des_crackeddirt1"] = shaders["ground"],
	["des_rocky1"] = shaders["ground"],
	["des_rocky1_dirt1"] = shaders["ground"],
	["des_ripplsand"] = shaders["ground"],
	["parking1plain"] = shaders["ground"],
	["des_scrub1"] = shaders["ground"],
	["des_scrub1_dirt1"] = shaders["ground"],
	["des_1line256"] = shaders["road2"],
	["des_oldrunway"] = shaders["ground"],
	["des_oldrunwayblend"] = shaders["ground"],
	["des_panelconc"] = shaders["ground"],
	["des_dirttrackx"] = shaders["ground"],
	["des_grass2scrub"] = shaders["ground"],
	["golf_heavygrass"] = shaders["ground"],
	["golf_greengrass"] = shaders["ground"],
	["golf_fairway3"] = shaders["ground"],
	["golf_fairway1"] = shaders["ground"],
	["seabed"] = shaders["ground"],
	["des_dirt1_glfhvy"] = shaders["ground"],
	["vgs_rockmid1a"] = shaders["ground"],
	["vgs_rockbot1a"] = shaders["ground"],
	["grasslawnfade_256"] = shaders["ground"],
	["yardgrass1"] = shaders["ground"],
	["concretedust2_256128"] = shaders["ground"],
	["con2sand1c"] = shaders["ground"],
	["des_scrub1_dirt1a"] = shaders["ground"],
	["des_scrub1_dirt1b"] = shaders["ground"],
	["con2sand1a"] = shaders["ground"],
	["con2sand1b"] = shaders["ground"],
	["vegasdirtyroad1_256"] = shaders["road"],
	["vegasdirtypave1_256"] = shaders["ground"],
	["crossing_law3"] = shaders["ground"],
	["ws_carparknew2b"] = shaders["ground"],
	["hiwaymidlle_256"] = shaders["road"],
	["hiwayinside2_256"] = shaders["ground"],
	["hiwaygravel1_256"] = shaders["ground"],
	["hiway2sand1a"] = shaders["ground"],
	["hiwayoutside_256"] = shaders["ground"],
	["hiwayinside4_256"] = shaders["ground"],
	["hiwayinside5_256"] = shaders["ground"],
	["hiwayinside3_256"] = shaders["ground"],
	["hiwayinside1_256"] = shaders["ground"],
	["hiwayend_256"] = shaders["road"],
	["venturas_fwend"] = shaders["ground"],
	["tar_venturasjoin"] = shaders["road2"],
	["tar_1linefreewy"] = shaders["road2"],
	["block"] = shaders["ground"],
	["tar_lineslipway"] = shaders["road2"],
	["stormdrain5_nt"] = shaders["ground"],
	["des_dirt2gygrass"] = shaders["ground"],
	["rocktbrn128blndlit"] = shaders["ground"],
	["blendrock2grgrass"] = shaders["ground"],
	["sfn_rocktbrn128"] = shaders["ground"],
	["sfn_rockhole"] = shaders["ground"],
	["sfn_grass1"] = shaders["ground"],
	["hedge1"] = shaders["newhedgea"],
	["sf_junction2"] = shaders["ground"],
	["greyground256128"] = shaders["ground"],
	["ws_slatetiles"] = shaders["ground"],
	["ws_carpark1"] = shaders["ground"],
	["was_scrpyd_ground_muddier"] = shaders["ground"],
	["bow_church_dirt_to_grass_side_t"] = shaders["ground"],
	["ws_baseballdirt"] = shaders["ground"],
	["ws_rooftarmac2"] = shaders["ground"],
	["ws_asphalt2"] = shaders["ground"],
	["dustyconcrete"] = shaders["ground"],
	["ws_corr_metal2"] = shaders["ground"],
	["golf_grassrock"] = shaders["ground"],
	["golf_fairway2"] = shaders["ground"],
	["dt_road2grasstype4"] = shaders["ground"],
	["grass4dirty"] = shaders["ground"],
	["crazy paving"] = shaders["ground"],
	["cw2_mountdirt2forest"] = shaders["ground"],
	["grasstype510"] = shaders["ground"],
	["grasstype510_10"] = shaders["ground"],
	["grasstype10"] = shaders["ground"],
	["rocktq128blender"] = shaders["ground"],
	["grass10_stones256"] = shaders["ground"],
	["roadblendcunt"] = shaders["road2"],
	["forestfloorbranch256"] = shaders["ground"],
	["grassgrnbrnx256"] = shaders["ground"],
	["tar_1line256hvlightsand"] = shaders["road2"],
	["tar_1line256hvgtravel"] = shaders["road2"],
	["grass10forest"] = shaders["ground"],
	["grasstype10_rail"] = shaders["ground"],
	["grass10dirt"] = shaders["ground"],
	["grassdeep256"] = shaders["ground"],
	["grassdirtblend"] = shaders["road"],
	["forestfloor4"] = shaders["ground"],
	["grasstype4_staw"] = shaders["ground"],
	["grasstype4-3"] = shaders["ground"],
	["ws_traingravelblend"] = shaders["ground"],
	["ws_woodyhedge"] = shaders["newhedgea"],
	["veg_hedge1_256"] = shaders["newhedgea"],
	["txgrass0_1"] = shaders["grass"]
}

function applySnow(state)
	if (state) == true then
		for k, v in pairs(replaceTextures) do
			engineApplyShaderToWorldTexture(v, k)
		end
	elseif (state) == false then
		for k, v in pairs(replaceTextures) do
			engineRemoveShaderFromWorldTexture(v, k)
		end
	end
end

function loadPreference()
	if source ~= resourceRoot then return end
	if getSetting("snow") == "true" then
		applySnow(true)
	end
end
addEventHandler("onClientResourceStart", getRootElement(), loadPreference)


local settingsXMLFile = nil

function initSettings()
    settingsXMLFile = xmlLoadFile("settings.xml")
    if not settingsXMLFile then
        settingsXMLFile = xmlCreateFile("settings.xml", "settings")
        setSetting("snow", "true") -- set defaults
    end
end
addEventHandler("onClientResourceStart", resourceRoot, initSettings)

function toggleSnow()
    snowOn = getSetting("snow")

    if (snowOn) == "false" then
        setSetting("snow", "true")
		applySnow(true)
        outputChatBox("Snow has been enabled!")
    else
        setSetting("snow", "false")
		applySnow(false)
        outputChatBox("Snow has been disabled!")
    end
end
addCommandHandler("snow", toggleSnow)

function setSetting(setting, value)
    if value then
        value = tostring(value)
        xmlNodeSetAttribute(settingsXMLFile, setting, value)
    end
    xmlSaveFile(settingsXMLFile)
end

function getSetting(setting)
    if setting then
        local val = xmlNodeGetAttribute(settingsXMLFile, setting)
        if val then
            return val
        else
            return false
        end
    else
        return false
    end
end